apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: hammoq-client-test
  name: hammoq-client-test
  namespace: default
  selfLink: /api/v1/namespaces/default/services/hammoq-client-test
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: hammoq-client-test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}